export const LOAD_USER = "LOAD_USER";
export const ADD_CATEGORY = "ADD_CATEGORY";
export const DELETE_CATEGORY = "DELETE_CATEGORY";
export const ADD_STORE = "ADD_STORE";
export const DELETE_STORE = "DELETE_STORE";
export const ADD_TEMPLATE = "ADD_TEMPLATE";
export const DELETE_TEMPLATE = "DELETE_TEMPLATE";
export const UPDATE_TEMPLATE = "UPDATE_TEMPLATE";

export const LOAD_FINANCEDATA = "LOAD_FINANCEDATA";
export const ADD_FINANCEDP = "ADD_FINANCEDP";
export const UPDATE_FINANCEDP = "UPDATE_FINANCEDP";
export const DELETE_FINANCEDP = "DELETE_FINANCEDP";
